namespace: sales-test-ns

services:
  auth:
    image: kubectlandchill/auth-service:v1
    port: 3000
    replicas: 2
    probe: true

  customer:
    image: kubectlandchill/customer-service:v1
    port: 3000
    replicas: 2
    probe: true

  order:
    image: kubectlandchill/order-service:v1
    port: 3000
    replicas: 2
    probe: true

  invoice:
    image: kubectlandchill/invoice-service:v1
    port: 3000
    replicas: 2
    probe: true

  payment:
    image: kubectlandchill/payment-service:v1
    port: 3000
    replicas: 2
    probe: true

  sales-ui:
    image: kubectlandchill/sales-invoice-ui:v1.1.2
    port: 3000
    replicas: 2
    probe: false

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  cpuUtilization: 70

database:
  enabled: true
  image: mysql:8.4
  storage: 2Gi

gateway:
  enabled: true
  port: 80

routes:
  auth:
    path: /api/auth
    service: auth-service

  customers:
    path: /api/customers
    service: customer-service

  orders:
    path: /api/orders
    service: order-service

  invoices:
    path: /api/invoices
    service: invoice-service

  payments:
    path: /api/payments
    service: payment-service

  ui:
    path: /
    service: sales-ui-service