global:
  environment: dev
  imagePullPolicy: IfNotPresent

namespaces:
  application: sales-test-ns
  gateway: sales-gateway-ns

# ---------------- CONFIGMAPS ----------------

configmaps:
  backend:
    name: backend-config
    data:
      AUTH_SERVICE_URL: http://auth-service:3000
      NOTIFICATION_SERVICE_URL: http://notification-service:3000
      CUSTOMER_SERVICE_URL: http://customer-service:3000
      ORDER_SERVICE_URL: http://order-service:3000
      INVOICE_SERVICE_URL: http://invoice-service:3000
      PAYMENT_SERVICE_URL: http://payment-service:3000

  frontend:
    name: frontend-config
    data:
      NEXT_PUBLIC_API_URL: /api/v1


# ---------------- SECRETS ----------------

secrets:

  backend:
    name: backend-secret
    data:
      DATABASE_URL: mysql+pymysql://salesuser:salespassword@mysql-db:3306/sales_db
      JWT_SECRET_KEY: djnjenjnejnjdennekwnkndekwnkjndejkwnjkdnekwjndjkwnekjdnekjwndkjnwekndkwenkjdnwekjncdjnjnjdn
      ENVIRONMENT: production
      ACCESS_TOKEN_EXPIRE_MINUTES: "360"
      RABBITMQ_URL: amqp://salesuser:salespassword@rabbitmq:5672/
      API_URL: /api/v1

    mysql:
      name: mysql-secret
      data:
        MYSQL_ROOT_PASSWORD: rootpassword
        MYSQL_DATABASE: sales_db
        MYSQL_USER: salesuser
        MYSQL_PASSWORD: salespassword

    rabbitmq:
      name: rabbitmq-secret
      data:
        RABBITMQ_DEFAULT_USER: salesuser
        RABBITMQ_DEFAULT_PASS: salespassword

# ---------------- SERVICES ----------------

auth:
  name: auth-deployment
  replicaCount: 2
  port: 3000
  image:
    repository: kubectlandchill/sales-auth-service
    tag: v1.2.2
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "200m"
      memory: "512Mi"

customer:
  name: customers-deployment
  replicaCount: 2
  port: 3000
  image:
    repository: kubectlandchill/sales-customer-service
    tag: v1.2.2
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "200m"
      memory: "512Mi"

order:
  name: order-deployment
  replicaCount: 2
  port: 3000
  image:
    repository: kubectlandchill/sales-order-service
    tag: v1.2.2
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "200m"
      memory: "512Mi"

invoice:
  name: invoice-deployment
  replicaCount: 2
  port: 3000
  image:
    repository: kubectlandchill/sales-invoice-service
    tag: v1.1.1
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "200m"
      memory: "512Mi"

payment:
  name: payment-deployment
  replicaCount: 2
  port: 3000
  image:
    repository: kubectlandchill/sales-payment-service
    tag: v1.1.1
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "200m"
      memory: "512Mi"

notifications:
  name: notification-deployment
  replicaCount: 2
  port: 3000
  image:
    repository: kubectlandchill/sales-notification-service
    tag: v1.0.2

salesUi:
  name: sales-ui-deployment
  replicaCount: 2
  port: 3000
  image:
    repository: kubectlandchill/sales-invoice-ui
    tag: v1.1.5
  resources:
    requests:
      cpu: "100m"
      memory: "512Mi"
    limits:
      cpu: "250m"
      memory: "720Mi"

# ---------------- HPA ----------------

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  cpuUtilization: 70

# ---------------- DATABASE ----------------

storage:
  storageClassName: sales-storageclass
  provisioner: nfs.csi.k8s.io
  parameters:
    server: 65.0.107.237
    share: /var/nfs/sales-microservice/test
  reclaimPolicy: Retain
  volumeBindingMode: Immediate

  rabbitmq:
    stsName: rabbitmq
    volumeMountPath: /var/lib/rabbitmq
    replicaCount: 1
    storageSize: 5Gi
    accessModes: ReadWriteMany
    vctName: rabbitmq-data
    image:
      repository: rabbitmq
      tag: 3-management


  mysql:
    stsName: mysql-db
    volumeMountPath: /var/lib/mysql
    replicaCount: 1
    storageSize: 5Gi
    accessModes: ReadWriteMany
    vctName: mysql-data
    image:
      repository: mysql
      tag: 8.4
  

# ---------------- GATEWAY ----------------

gateway:
  gatewayName: sales-gateway
  namespace: sales-gateway-ns
  gatewayClassName: kgateway
  listeners:
    port: 80
  enabled: true
  port: 80

# ---------------- ROUTES ----------------

routes:
  auth:
    routeName: auth-route
    path: /api/v1/auth
    service: auth-service
    port: 3000

  customers:
    routeName: customer-route
    path: /api/v1/customers
    service: customer-service
    port: 3000

  orders:
    routeName: order-route
    path: /api/v1/orders
    service: order-service
    port: 3000

  invoices:
    routeName: invoice-route
    path: /api/v1/invoices
    service: invoice-service
    port: 3000

  payments:
    routeName: payment-route
    path: /api/v1/payments
    service: payment-service
    port: 3000

  notifications:
    routeName: notifications-route
    path: /api/v1/notifications
    service: notification-service
    port: 3000

  ui:
    routeName: frontend-route
    path: /
    service: sales-ui-service
    port: 8000

  mysql:
    service: mysql-db
    port: 3306

  rabbitmq:
    service: rabbitmq-service
    port: 5672