apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.auth.name }}
  namespace: {{ .Values.namespaces.application }}
  labels:
    app: auth
spec:
  replicas: {{ .Values.auth.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: auth-microservice
  template:
    metadata:
      labels:
        app: auth-microservice
    spec:
      containers:
        - name: auth-container
          image: {{ .Values.auth.image.repository }}:{{ .Values.auth.image.tag }}
          ports:
            - containerPort: {{ .Values.auth.port }}
          envFrom:
            - secretRef:
                name: backend-secret
            - configMapRef:
                name: {{ .Values.configmaps.backend.name }}
          resources:
            limits:
              cpu: {{ .Values.auth.resources.limits.cpu }}
              memory: {{ .Values.auth.resources.limits.memory }}
            requests:
              cpu: {{ .Values.auth.resources.requests.cpu }}
              memory: {{ .Values.auth.resources.requests.memory }}