apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.salesUi.name }}
  namespace: {{ .Values.namespaces.application }}
  labels:
    app: sales-ui 
spec:
  replicas: {{ .Values.salesUi.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: sales-ui
  template:
    metadata:
      labels:
        app: sales-ui
    spec:
      containers:
        - name: sales-ui-container
          image: {{ .Values.salesUi.image.repository }}:{{ .Values.salesUi.image.tag }}
          ports:
            - containerPort: {{ .Values.salesUi.port }}
          resources:
            requests:
              cpu: {{ .Values.salesUi.resources.requests.cpu }}
              memory: {{ .Values.salesUi.resources.requests.memory }}
            limits:
              cpu: {{ .Values.salesUi.resources.limits.cpu }}
              memory: {{ .Values.salesUi.resources.limits.memory }}
          envFrom:
            - secretRef:
                name: {{ .Values.secrets.frontend.name }}
            - configMapRef:
                name: {{ .Values.configmaps.frontend.name }}