apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.invoice.name }}
  namespace: {{ .Values.namespaces.application }}
  labels:
    app: invoice
spec:
  replicas: {{ .Values.invoice.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: invoice-microservice
  template:
    metadata:
      labels:
        app: invoice-microservice
    spec:
      containers:
      - name: invoice-container
        image: {{ .Values.invoice.image.repository }}:{{ .Values.invoice.image.tag }}
        ports:
        - containerPort: {{ .Values.invoice.port }}
        envFrom:
        - secretRef:
            name: backend-secret
        - configMapRef:
            name: {{ .Values.configmaps.backend.name }}
        resources:
          limits:
            memory: {{ .Values.invoice.resources.limits.memory }}
            cpu: {{ .Values.invoice.resources.limits.cpu }}
          requests:
            memory: {{ .Values.invoice.resources.requests.memory }}
            cpu: {{ .Values.invoice.resources.requests.cpu }}