apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Values.namespaces.gateway }}
spec:
  gatewayClassName: {{ .Values.gateway.gatewayClassName }}
  listeners:
    - name: http
      port: {{ .Values.gateway.listeners.port }}
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              shared-gateway: "true"