apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.routes.customers.service }}
  namespace: {{ .Values.namespaces.application }}
  labels:
    app: customers
spec:
  type: ClusterIP
  selector:
    app: customers-microservice
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      