apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.routes.auth.routeName }}
  namespace: {{ .Values.namespaces.application }}
spec:
  parentRefs:
    - name: {{ .Values.gateway.gatewayName }}
      namespace: {{ .Values.namespaces.gateway }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: {{ .Values.routes.auth.path }}
      backendRefs:
        - name: {{ .Values.routes.auth.service }}
          port: {{ .Values.routes.auth.port }}