apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.backend.name }}
  namespace: {{ .Values.namespaces.application }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secrets.backend.data.DATABASE_URL }}
  JWT_SECRET_KEY: {{ .Values.secrets.backend.data.JWT_SECRET_KEY }}
  ENVIRONMENT: {{ .Values.secrets.backend.data.ENVIRONMENT }}
  ACCESS_TOKEN_EXPIRE_MINUTES: {{ .Values.secrets.backend.data.ACCESS_TOKEN_EXPIRE_MINUTES }}
  RABBITMQ_URL: {{ .Values.secrets.backend.data.RABBITMQ_URL }}
  API_URL: {{ .Values.secrets.backend.data.API_URL }}