apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: {{ .Values.namespaces.application }}
type: Opaque
stringData:
  DATABASE_URL: mysql+pymysql://salesuser:salespassword@mysql-db:3306/sales_db
  JWT_SECRET_KEY: djnjenjnejnjdennekwnkndekwnkjndejkwnjkdnekwjndjkwnekjdnekjwndkjnwekndkwenkjdnwekjncdjnjnjdn
  ENVIRONMENT: production
  ACCESS_TOKEN_EXPIRE_MINUTES: "360"
  RABBITMQ_URL: amqp://salesuser:salespassword@rabbitmq:5672/
  API_URL: /api/v1