apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: {{ .Values.namespaces.application }}
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootpassword
  MYSQL_DATABASE: sales_db
  MYSQL_USER: salesuser
  MYSQL_PASSWORD: salespassword