apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.mysql.name }}
  namespace: {{ .Values.namespaces.application }}
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.secrets.mysql.data.MYSQL_ROOT_PASSWORD }}
  MYSQL_DATABASE: {{ .Values.secrets.mysql.data.MYSQL_DATABASE }}
  MYSQL_USER: {{ .Values.secrets.mysql.data.MYSQL_USER }}
  MYSQL_PASSWORD: {{ .Values.secrets.mysql.data.MYSQL_PASSWORD }}