apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
  namespace: {{  .Values.namespaces.application }}
type: Opaque
stringData:
  SMTP_HOST: smtp.hostinger.com
  SMTP_PORT: "587"
  SMTP_USER:
  SMTP_PASS: 
  FROM_EMAIL: notification@opslora.com
  FROM_NAME: Opslora