apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: {{ .Values.namespaces.application }}
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: salesuser
  RABBITMQ_DEFAULT_PASS: salespassword