apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.rabbitmq.name }}
  namespace: {{ .Values.namespaces.application }}
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: {{ .Values.secrets.rabbitmq.data.RABBITMQ_DEFAULT_USER }}
  RABBITMQ_DEFAULT_PASS: {{ .Values.secrets.rabbitmq.data.RABBITMQ_DEFAULT_PASS }}