apiVersion: apps/v1
kind: Deployment
metadata:
  name: customers-deployment
  namespace: sales-test-ns
  labels:
    app: customers
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: customers-microservice
  template:
    metadata:
      labels:
        app: customers-microservice
    spec:
      containers:
        - name: customers-container
          image: kubectlandchill/sales-customer-service:v1.1.0
          resources:
            limits:
              memory: "512Mi"
              cpu: "200m"
            requests:
              memory: "256Mi"
              cpu: "100m"
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: backend-secret
            - configMapRef:
                name: backend-config