apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
  namespace: sales-test-ns
  labels:
    app: payment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: payment-microservice
  template:
    metadata:
      labels:
        app: payment-microservice
    spec:
      containers:
        - name: payment-container
          image: kubectlandchill/sales-payment-service:v1.1.0
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "512Mi"
              cpu: "200m"
            requests:
              memory: "256Mi"
              cpu: "100m"
          envFrom:
            - secretRef:
                name: backend-secret
            - configMapRef:
                name: backend-config