apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmaps.backend.name }}
  namespace: {{ .Values.namespaces.application }}
data:
  CUSTOMER_SERVICE_URL: {{ .Values.configmaps.backend.data.CUSTOMER_SERVICE_URL }}
  ORDER_SERVICE_URL: {{ .Values.configmaps.backend.data.ORDER_SERVICE_URL }}
  INVOICE_SERVICE_URL: {{ .Values.configmaps.backend.data.INVOICE_SERVICE_URL }}