apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: {{ .Values.namespaces.application }}
data:
  CUSTOMER_SERVICE_URL: http://customer-service:3000
  ORDER_SERVICE_URL: http://order-service:3000
  INVOICE_SERVICE_URL: http://invoice-service:3000