apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmaps.frontend.name }}
  namespace: {{ .Values.namespaces.application }}
data:
  NEXT_PUBLIC_API_URL: {{ .Values.configmaps.frontend.data.NEXT_PUBLIC_API_URL }}