apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.storage.mysql.stsName }}
  namespace: {{ .Values.namespaces.application }}
  labels:
    app: mysql
spec:
  serviceName: {{ .Values.routes.mysql.service }}
  replicas: {{ .Values.storage.mysql.replicaCount }}

  selector:
    matchLabels:
      app: mysql

  template:
    metadata:
      labels:
        app: mysql

    spec:
      containers:
        - name: mysql
          image: {{ .Values.storage.mysql.image.repository }}:{{ .Values.storage.mysql.image.tag }}

          ports:
            - containerPort: 3306

          envFrom:
            - secretRef:
                name: mysql-secret

          volumeMounts:
            - name: mysql-data
              mountPath: {{ .Values.storage.mysql.volumeMountPath }}

  volumeClaimTemplates:
  - metadata:
      name: {{ .Values.storage.mysql.vctName }}
    spec:
      storageClassName: {{ .Values.storage.storageClassName }}
      accessModes:
      - {{ .Values.storage.mysql.accessModes }}
      resources:
        requests:
          storage: {{ .Values.storage.mysql.storageSize }}