apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.storage.rabbitmq.stsName }}
  namespace: {{ .Values.namespaces.application }}
  labels:
    app: rabbitmq
spec:
  serviceName: {{ .Values.routes.rabbitmq.service }}
  replicas: 1
 
  selector:
    matchLabels:
      app: rabbitmq
 
  template:
    metadata:
      labels:
        app: rabbitmq
 
    spec:
      containers:
        - name: rabbitmq
          image: {{ .Values.storage.rabbitmq.image.repository }}:{{ .Values.storage.rabbitmq.image.tag }}
 
          ports:
            - containerPort: 5672
            - containerPort: 15672
 
          envFrom:
            - secretRef:
                name: rabbitmq-secret
 
          volumeMounts:
            - name: rabbitmq-data
              mountPath: {{ .Values.storage.rabbitmq.volumeMountPath }}
 
  volumeClaimTemplates:
    - metadata:
        name: rabbitmq-data
      spec:
        storageClassName: {{ .Values.storage.storageClassName }}
        accessModes:
          - {{ .Values.storage.rabbitmq.accessModes }}
        resources:
          requests:
            storage: {{ .Values.storage.rabbitmq.storageSize }}