apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: sales-test-ns
  labels:
    app: payment
spec:
  selector:
    app: payment-microservice
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP